name: Build & deploy the Lambda layer.
env:
  NPM_PACKAGES: lodash
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2.1.5
    - run: npm install $NPM_PACKAGES
    - uses: ItsKarma/aws-cli@v1.70.0
    - run: aws --version
