name: Build & deploy the Lambda layer.
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2.1.5
    - run: npm install lodash
